name: chavelli
favicon: null
layout_spectrum: 0.9530333746224642
typography_spectrum: 0.6124558572191745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7793248447123915
  lightness: 0.024645241908729076
  saturation: 0.8904969340655953
  rhythmicContrast: 0.44105410668998957
purpose: []
